# Generated by Django 2.0.4 on 2018-05-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180502_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='height_image',
            new_name='avatar_height',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='width_image',
            new_name='avatar_width',
        ),
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, height_field='avatar_height', null=True, upload_to='avatars', width_field='avatar_width'),
        ),
    ]
