# Generated by Django 2.0.4 on 2018-05-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180506_0017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': (('approve', 'Can approve comments'),)},
        ),
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default='avatars/default-user.png', height_field='avatar_height', upload_to='avatars', width_field='avatar_width'),
        ),
    ]
