# Generated by Django 2.0.4 on 2018-05-10 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180509_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': (('approve_comment', 'Can approve comments'),)},
        ),
    ]
