# Generated by Django 2.0.4 on 2018-05-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_likedislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация:'),
        ),
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default-user.png', height_field='avatar_height', upload_to='avatars', verbose_name='Фото:', width_field='avatar_width'),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения:'),
        ),
        migrations.AlterField(
            model_name='author',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Страна:'),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='Имя:'),
        ),
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, null=True, verbose_name='Пол:'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='Фамилия:'),
        ),
        migrations.AlterField(
            model_name='author',
            name='nickname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ник/Имя пользователя:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_image', null=True, upload_to='posts', verbose_name='Фото', width_field='width_image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
